### ISSUE TITLE
Feature requests for next version

### ISSUE THREAD

**Issue by kenm-4682** [bitfocus/companion-module-bmd-webpresenter#1]
I have been using this for a few weeks and am really enjoying it! Thanks!

I have a few feature requests:

1. Being able to input / change the stream key - pg31-32 of manual
Use case: I use a Web Presenter HD at a venue that does 2 back-to-back streams to YT, with the same stream keys every week -- being able to flip the stream from one stream key to another stream key via Companion would make this super quick (versus manually entering the stream key on the Web Presenter Setup computer app every week)

2. More robust monitoring of stream status (not just "off air / on air") - pg34
Use case: the manual shows status options including Idle/Connecting/Streaming/Interrupted; along with displaying Bitrate and Stream Duration; all of which would be great to monitor from a Stream Deck

3. Ability to reboot - pg35
Use case: It's Blackmagic -- so sometimes it just needs a restart

Manual w/ control & monitoring protocols:
https://documents.blackmagicdesign.com/UserManuals/BlackmagicWebPresenterHDManual.pdf

**Comment by daniep01** [comment]
Hi,

Glad you're finding it useful, I'm pleased that it works at all as I don't have one to test with myself. 

Adding the reboot is easy so that is now done and should be in the beta of companion in a few days. Please report back if it works or not.

The monitoring should already be available in a variable - can you check this? In addition to the variable what else would you like to do with this data?

Stream Keys can be added, I will look at this next.
